version: '4'
services:
  front-docker:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:443"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /home/dohttps/nginx/data/.well-known/pki-validation:/usr/share/nginx/html/.well-known/pki-validation/
      - /home/dohttps/nginx:/var/log/nginx/
      - /home/dohttps/nginx/ssl:/ssl/
networks:
    default:
      external:
        name: project2-net